version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root

  backend:
    build: 
      context: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    
  frontend:
    build: 
      context: ./Frontend/my-app
    ports:
      - "3000:3000"

  